/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module multiple_module_opt(a, b, c, d, y);
  wire _0_;
  wire \U1.y ;
  input a;
  input b;
  input c;
  input d;
  output y;
  assign _0_ = \U1.y  & b;
  assign y = _0_ | c;
  assign \U1.y  = 1'h1 & a;
endmodule
