/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module multiple_module_opt2(a, b, c, d, y);
  wire \U1.y ;
  wire \U2.y ;
  wire \U3.y ;
  input a;
  input b;
  input c;
  input d;
  output y;
  assign \U1.y  = 1'h0 & a;
  assign \U2.y  = c & b;
  assign \U3.y  = d & \U2.y ;
  assign y = \U1.y  & \U3.y ;
endmodule
